[project]
name = "react_agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "requests>=2.31.0",
    "pyperclip>=1.8.2",
]

[tool.uv.workspace]
members = [
    "snake3",
]
